(function(root,factory){const api=factory(root,typeof module==='object'&&module.exports?require('./audio-synth.js'):root.ImranAudioSynth);if(typeof module==='object'&&module.exports)module.exports=api;else root.ImranAudio=api})(typeof globalThis!=='undefined'?globalThis:this,(root,synth)=>{'use strict';
const tracks={menu:'music-menu.wav',battle:'music-battle.wav',boss:'music-boss.wav',victory:'music-victory.wav'};
function create(options={}){
 const settings=options.settings||(()=>({sound:true,music:true,voice:true,masterVolume:80,musicVolume:55,effectsVolume:70,voiceVolume:90})),fetcher=options.fetch||root.fetch?.bind(root),report=options.onStatus||(()=>{});
 let ctx=null,master=null,musicBus=null,effectsBus=null,voiceBus=null,scene='menu',paused=false,unlocked=false,loading=null,loaded=false,failed=false,voiceMap=options.voiceMap||root.ImranAudioVoiceMap||null,voice=null,pending=null,voiceSerial=0,welcomePlayed=false,endedVictory=false;
 const buffers=new Map(),effects=new Set(),music=new Set(),effectTimes=new Map(),voiceTimes=new Map(),effectBuffers=new Map();
 function volume(key,fallback){const n=Number(settings()[key]);return Number.isFinite(n)?Math.max(0,Math.min(1,n/100)):fallback}
 function status(){report(!settings().sound?'Звук выключен':!ctx?'Коснись экрана, чтобы запустить звук':paused?'Аудио на паузе':loading&&!loaded?'Подготавливаем аудио…':failed?'Часть аудио недоступна. Звуки оружия работают.':unlocked?'Музыка и озвучка готовы':'Нажми «Прослушать», чтобы включить звук')}
 function gain(node,value,time=.08){if(!node||!ctx)return;try{node.gain.cancelScheduledValues(ctx.currentTime);node.gain.setTargetAtTime(value,ctx.currentTime,time)}catch{node.gain.value=value}}
 function apply(){const s=settings();gain(master,s.sound?volume('masterVolume',.8):0);gain(effectsBus,volume('effectsVolume',.7));gain(voiceBus,s.voice?volume('voiceVolume',.9):0);gain(musicBus,s.music?volume('musicVolume',.55)*(voice ? .35 : 1):0);if(!s.voice)stopVoice();if(!s.sound){pending=null;stopEffects();stopVoice();stopMusic();ctx?.suspend().catch(()=>{});unlocked=false}else if(ctx&&!paused){ctx.resume().then(()=>{unlocked=ctx.state==='running';playMusic();status()}).catch(()=>status())}if(!s.music)stopMusic();else playMusic();status()}
 function build(){if(ctx)return true;try{const C=root.AudioContext||root.webkitAudioContext;ctx=options.contextFactory?options.contextFactory():C?new C():null;if(!ctx){report('Это устройство не поддерживает игровое аудио');return false}master=ctx.createGain();musicBus=ctx.createGain();effectsBus=ctx.createGain();voiceBus=ctx.createGain();const compressor=ctx.createDynamicsCompressor();compressor.threshold.value=-12;compressor.knee.value=18;compressor.ratio.value=4;compressor.attack.value=.008;compressor.release.value=.18;musicBus.connect(master);effectsBus.connect(master);voiceBus.connect(master);master.connect(compressor);compressor.connect(ctx.destination);apply();return true}catch{ctx=null;report('Не удалось запустить аудио. Попробуй ещё раз.');return false}}
 async function decode(file){if(buffers.has(file))return buffers.get(file);if(!fetcher)throw Error('No audio loader');const response=await fetcher(file);if(!response.ok)throw Error('Audio asset unavailable');const buffer=await ctx.decodeAudioData(await response.arrayBuffer());buffers.set(file,buffer);return buffer}
 function load(){if(loading)return loading;loading=(async()=>{const jobs=Object.values(tracks).map(file=>decode(file));jobs.push(decode('audio-voice.wav'));if(!voiceMap)jobs.push((async()=>{const r=await fetcher('voice-map.json');if(!r.ok)throw Error('No voice map');voiceMap=await r.json()})());const results=await Promise.allSettled(jobs);failed=results.some(r=>r.status==='rejected');loaded=true;playMusic();if(pending){const cue=pending;pending=null;if(ctx.currentTime-cue.time<4)speak(cue.id,cue.priority,true)}status()})();return loading}
 async function unlock(){if(paused)return false;if(!settings().sound){status();return false}if(!build())return false;try{await ctx.resume();if(paused){await ctx.suspend();return false}unlocked=ctx.state==='running';if(unlocked&&!paused){load();playMusic();if(scene==='menu'&&!welcomePlayed){welcomePlayed=true;speak('welcome',1)}}status();return unlocked}catch{status();return false}}
 function stopEffects(){for(const source of effects){try{source.stop()}catch{}source.disconnect()}effects.clear()}
 function stopVoice(){voiceSerial++;pending=null;if(voice){const old=voice;voice=null;try{old.source.stop()}catch{}old.source.disconnect()}gain(musicBus,settings().music?volume('musicVolume',.55):0,.18)}
 function stopMusic(){for(const item of music){item.closing=true;try{item.source.stop()}catch{}item.source.disconnect();item.gain.disconnect()}music.clear()}
 function playMusic(){if(!ctx||ctx.state!=='running'||paused||!settings().sound||!settings().music||!tracks[scene]||(scene==='victory'&&endedVictory))return;const key=tracks[scene],buffer=buffers.get(key);if(!buffer||[...music].some(m=>m.key===key&&!m.closing))return;
 // At most two music sources exist, even when scenes switch repeatedly.
 for(const item of music){if(item.closing){try{item.source.stop()}catch{}item.source.disconnect();item.gain.disconnect();music.delete(item)}else{item.closing=true;gain(item.gain,0,.2);try{item.source.stop(ctx.currentTime+.85)}catch{}}}
 const source=ctx.createBufferSource(),level=ctx.createGain(),item={source,gain:level,key,closing:false};source.buffer=buffer;source.loop=scene!=='victory';level.gain.value=0;source.connect(level);level.connect(musicBus);source.onended=()=>{source.disconnect();level.disconnect();music.delete(item);if(item.key===tracks.victory&&!item.closing)endedVictory=true};music.add(item);source.start();gain(level,1,.22)
 }
 function setScene(value,restart=false){const next=value==='results'?'victory':value;if(next===scene&&!restart){playMusic();return}if(next!==scene||restart)endedVictory=false;scene=next;pending=null;if(restart)stopMusic();playMusic();if(!tracks[scene])stopMusic()}
 function effect(name,amount=1){if(!ctx||ctx.state!=='running'||paused||!settings().sound||volume('effectsVolume',.7)===0||effects.size>=18)return false;const gap=name==='ui'?.04:name==='explosion'?.08:.045,now=ctx.currentTime;if(now-(effectTimes.get(name)??-Infinity)<gap)return false;effectTimes.set(name,now);let buffer=effectBuffers.get(name);if(!buffer){const data=synth.effect(name,ctx.sampleRate);buffer=ctx.createBuffer(1,data.length,ctx.sampleRate);buffer.copyToChannel(data,0);effectBuffers.set(name,buffer)}const source=ctx.createBufferSource(),level=ctx.createGain();source.buffer=buffer;level.gain.value=Math.max(.1,Math.min(1,amount))*.65;source.connect(level);level.connect(effectsBus);effects.add(source);source.onended=()=>{source.disconnect();level.disconnect();effects.delete(source)};source.start();return true}
 function speak(id,priority=2,fromQueue=false){if(!ctx||paused||!settings().sound||!settings().voice||volume('voiceVolume',.9)===0)return false;const now=ctx.currentTime;if(!fromQueue&&now-(voiceTimes.get(id)??-Infinity)<(id==='critical'?12:2))return false;if(voice&&voice.priority>priority)return false;
 const clip=voiceMap?.[id],buffer=buffers.get('audio-voice.wav');if(!clip||!buffer){if(!loaded&&(!pending||priority>=pending.priority))pending={id,priority,time:now};return false}
 if(!Number.isFinite(clip.offset)||!Number.isFinite(clip.duration)||clip.offset<0||clip.duration<=0||clip.offset+clip.duration>buffer.duration+.02)return false;
 stopVoice();voiceTimes.set(id,now);const source=ctx.createBufferSource(),serial=++voiceSerial;source.buffer=buffer;source.connect(voiceBus);voice={source,priority,id,serial};gain(musicBus,settings().music?volume('musicVolume',.55)*.35:0,.04);source.onended=()=>{source.disconnect();if(voice?.serial===serial){voice=null;gain(musicBus,settings().music?volume('musicVolume',.55):0,.18)}};source.start(now,clip.offset,clip.duration);return true
 }
 function pause(){paused=true;pending=null;stopVoice();stopEffects();ctx?.suspend().catch(()=>{});status()}
 async function resume(){paused=false;await unlock();apply();status()}
 function stop(){pause();stopMusic();scene='menu'}
 return{unlock,load,apply,setScene,effect,speak,pause,resume,stop,stopVoice,get state(){return{scene,paused,unlocked,loaded,failed,activeEffects:effects.size,activeMusic:music.size,voice:voice?.id||null,pending:pending?.id||null}}}
}
return{create,tracks};});
