(function(root){'use strict';
const worlds=[
 {name:'Орбита Земли',code:'TERRA',color:'#69d8ef',shade:'rgba(5,32,60,.36)',planet:['#89b8cf','#305c7f','#08172e'],style:'orbit',story:'Последний свободный порт ждёт подкрепление.'},
 {name:'Рубеж Марса',code:'ARES',color:'#ffab75',shade:'rgba(70,19,13,.44)',planet:['#d89764','#803c36','#241327'],style:'dust',story:'Враг перекрыл транспортные коридоры Марса.'},
 {name:'Ледяной пояс',code:'BOREAL',color:'#9feeff',shade:'rgba(12,42,57,.46)',planet:['#d3eef2','#4c8197','#112431'],style:'ice',story:'Скрытая эскадра прячется в ледяном тумане.'},
 {name:'Туманность Вега',code:'VEGA',color:'#c5a1ff',shade:'rgba(50,15,78,.46)',planet:['#a993cd','#5d397b','#1b1537'],style:'nebula',story:'Сигнал командира теряется среди теневых флотов.'},
 {name:'Грозовой фронт',code:'TEMPEST',color:'#a4f5ad',shade:'rgba(10,52,34,.48)',planet:['#acd5a5','#3c7564','#0a252b'],style:'storm',story:'Ионные бури питают защитные установки врага.'},
 {name:'Сердце Улья',code:'NEMESIS',color:'#ffd684',shade:'rgba(58,34,13,.43)',planet:['#dbc284','#8c604c','#241a31'],style:'hive',story:'Источник вторжения близко. Флот прикрывает ядро.'}
];
const names=[['Первый контакт','Крылья тревоги','Разорвать строй','Линия обороны','Страж орбиты'],['Красная пыль','Охота на конвой','Штурм рубежа','Стальные ворота','Титан Марса'],['Холодный след','Ледяные клинья','Разведка боем','Белый перехват','Архонт льда'],['Тихая частота','Призрачный строй','Танец охотников','Теневая армада','Глаз Веги'],['Ионный след','Разрядный коридор','Зелёный фронт','Сердце бури','Повелитель гроз'],['Порог Улья','Золотой конвой','Защитники ядра','Последняя эскадра','Немезида']];
const styles=['patrol','wedge','crossfire','armada','siege'];
const missions=names.flatMap((group,world)=>group.map((name,slot)=>({id:world*5+slot+1,world,slot,name,duration:54+world*7+slot*8,formation:styles[(slot+world)%5],objective:slot===1||slot===3?'salvage':slot===2?'elite':'destroy',target:slot===1||slot===3?5+world:slot===2?2+Math.floor(world/2):12+world*3,eliteRate:.08+world*.035+(slot===2?.14:0),spawn:.95-slot*.035-world*.025,boss:world,brief:worlds[world].story})));
const bossTypes=[
 {name:'СТРАЖ «ОРИОН»',title:'Страж Орион',c:'#8bd8ff',r:61,hp:118,kind:'guardian',patterns:['fan','aim','ring'],sprite:1},
 {name:'ДРЕДНОУТ «ТИТАН»',title:'Дредноут Титан',c:'#ffa879',r:72,hp:148,kind:'dreadnought',patterns:['ring','lanes','aim'],sprite:4},
 {name:'АРХОНТ «БОРЕЙ»',title:'Архонт Борей',c:'#a4eeff',r:67,hp:176,kind:'archon',patterns:['cross','fan','lanes','aim'],sprite:3},
 {name:'ОКО «ВЕГА»',title:'Око Веги',c:'#cda0ff',r:70,hp:205,kind:'eye',patterns:['spiral','aim','minions','ring'],sprite:0},
 {name:'ПОВЕЛИТЕЛЬ «ГРОМ»',title:'Повелитель Гром',c:'#a3f4b4',r:75,hp:236,kind:'tempest',patterns:['lanes','cross','spiral','minions'],sprite:2},
 {name:'УЛЕЙ «НЕМЕЗИДА»',title:'Улей Немезида',c:'#ffd28e',r:80,hp:276,kind:'mothership',patterns:['minions','lanes','spiral','aim','cross'],sprite:5}
];
const upgrades={hull:{name:'Корпус',text:'Дополнительная жизнь на уровнях 2 и 4.',base:150,max:4},reactor:{name:'Реактор',text:'Каждый уровень повышает урон оружия на 8%.',base:170,max:5},magnet:{name:'Магнит',text:'Капсулы и сплав притягиваются с большего расстояния.',base:120,max:5},shield:{name:'Энергощит',text:'Защита на старте и больше времени от капсулы щита.',base:140,max:4},wingman:{name:'Ведомый',text:'Боевой дрон прикрывает ракету собственным лазером.',base:250,max:4},salvage:{name:'Сканер',text:'Больше сплава за завершённую миссию.',base:130,max:4}};
const ships=[{id:'pioneer',name:'Пионер',tag:'БАЛАНС',cost:0,unlock:1,text:'Надёжная ракета. Универсальный выбор для кампании.'},{id:'swift',name:'Стриж',tag:'СКОРОСТЬ',cost:700,unlock:6,text:'На 25% быстрее движение. Быстрее уклонение и перехват капсул.'},{id:'bastion',name:'Бастион',tag:'БРОНЯ',cost:1100,unlock:11,text:'Дополнительная жизнь и щит на старте. Скорость ниже на 12%.'}];
const key='imranStarDefender.v3';
const number=(value,min,max)=>Math.max(min,Math.min(max,Math.floor(Number(value)||0)));
function defaults(){return {version:3,credits:0,unlocked:1,selected:1,missions:{},upgrades:Object.fromEntries(Object.keys(upgrades).map(k=>[k,0])),arsenal:{laser:true,spread:false,plasma:false,rockets:false,beam:false},ships:['pioneer'],ship:'pioneer',endlessBest:0,settings:{sound:false,music:true,autoFire:true,reducedMotion:false,vibration:true,difficulty:'normal'}}}
function sanitize(raw){const state=defaults();if(!raw||typeof raw!=='object')return state;state.credits=number(raw.credits,0,9999999);state.unlocked=number(raw.unlocked,1,30);state.selected=number(raw.selected,1,state.unlocked);state.endlessBest=number(raw.endlessBest,0,99999999);for(const k of Object.keys(upgrades))state.upgrades[k]=number(raw.upgrades?.[k],0,upgrades[k].max);for(const k of Object.keys(state.arsenal))if(k!=='laser')state.arsenal[k]=raw.arsenal?.[k]===true;for(const ship of ships.slice(1))if(Array.isArray(raw.ships)&&raw.ships.includes(ship.id))state.ships.push(ship.id);if(state.ships.includes(raw.ship))state.ship=raw.ship;for(const k of ['sound','music','autoFire','reducedMotion','vibration'])if(typeof raw.settings?.[k]==='boolean')state.settings[k]=raw.settings[k];if(['easy','normal','hard'].includes(raw.settings?.difficulty))state.settings.difficulty=raw.settings.difficulty;for(const m of missions){const value=raw.missions?.[m.id];if(value&&typeof value==='object'&&number(value.stars,0,3)>0)state.missions[m.id]={stars:number(value.stars,1,3),score:number(value.score,0,99999999),clears:number(value.clears,1,999999)};}let contiguous=1;while(contiguous<30&&state.missions[contiguous])contiguous++;state.unlocked=contiguous;state.selected=Math.min(state.selected,contiguous);return state}
function createProfile(storage){let state=defaults(),storageAvailable=true;try{state=sanitize(JSON.parse(storage?.getItem(key)||'null'));}catch(error){storageAvailable=false}function save(){try{if(!storage)throw Error('Unavailable');storage.setItem(key,JSON.stringify(state));storageAvailable=true;return true}catch(error){storageAvailable=false;return false}}
return {get state(){return state},get storageAvailable(){return storageAvailable},save,select(id){id=number(id,1,30);if(id>state.unlocked)return false;state.selected=id;save();return true},setting(name,value){if(!Object.hasOwn(state.settings,name))return false;if(name==='difficulty'){if(!['easy','normal','hard'].includes(value))return false}else if(typeof value!=='boolean')return false;state.settings[name]=value;save();return true},unlockWeapon(type){if(!Object.hasOwn(state.arsenal,type)||state.arsenal[type])return false;state.arsenal[type]=true;save();return true},cost(type){const u=Object.hasOwn(upgrades,type)?upgrades[type]:null;return u?Math.round(u.base*Math.pow(1.65,state.upgrades[type])):Infinity},buy(type){const u=Object.hasOwn(upgrades,type)?upgrades[type]:null,cost=this.cost(type);if(!u||state.upgrades[type]>=u.max||state.credits<cost)return false;state.credits-=cost;state.upgrades[type]++;save();return true},selectShip(id){const ship=ships.find(s=>s.id===id);if(!ship)return false;if(!state.ships.includes(id)){if(state.unlocked<ship.unlock||state.credits<ship.cost)return false;state.credits-=ship.cost;state.ships.push(id);}state.ship=id;save();return true},award(id,stats){const m=missions[id-1];if(!m||id>state.unlocked)return null;const bonus=m.objective==='salvage'?stats.salvage>=m.target:m.objective==='elite'?stats.elites>=m.target:stats.kills>=m.target;const stars=1+Number(bonus)+Number(stats.damage===0),previous=state.missions[id],credits=Math.round((110+m.world*40+m.slot*15+number(stats.kills,0,1000)*3+number(stats.salvage,0,1000)*12+stars*25)*(1+state.upgrades.salvage*.12));state.missions[id]={stars:Math.max(stars,previous?.stars||0),score:Math.max(number(stats.score,0,99999999),previous?.score||0),clears:(previous?.clears||0)+1};state.unlocked=Math.max(state.unlocked,Math.min(30,id+1));state.selected=state.unlocked;state.credits=Math.min(9999999,state.credits+credits);save();return {stars,credits,bonus,complete:id===30}},awardEndless(score,kills){state.endlessBest=Math.max(state.endlessBest,number(score,0,99999999));const credits=Math.round(number(kills,0,5000)*4);state.credits=Math.min(9999999,state.credits+credits);save();return credits},reset(){state=defaults();save();}}}
function mission(id){return missions[number(id,1,30)-1]}
function goalText(m){return m.objective==='salvage'?'Собрать сплав: '+m.target:m.objective==='elite'?'Уничтожить элиту: '+m.target:'Уничтожить корабли: '+m.target}
const api={worlds,missions,bossTypes,upgrades,ships,createProfile,sanitize,mission,goalText,key};
if(typeof module==='object'&&module.exports)module.exports=api;else{root.ImranCampaign=api;let storage;try{storage=root.localStorage}catch(error){}api.profile=createProfile(storage)}
})(typeof globalThis!=='undefined'?globalThis:this);
