(()=>{'use strict';
// Gameplay clocks, firing, warnings and pickups advance only through update(dt).
const campaign=ImranCampaign,profile=campaign.profile;
const c=document.getElementById('game'),x=c.getContext('2d',{alpha:false});
const el=id=>document.getElementById(id);
const ui={top:el('top'),weapons:el('weapons'),hint:el('hint'),fire:el('fire'),pause:el('pause'),start:el('start'),over:el('over'),lives:el('lives'),score:el('score'),level:el('level'),best:el('best'),final:el('final'),finalBest:el('finalBest'),weaponName:el('weaponName'),weaponPower:el('weaponPower'),stageName:el('stageName'),stageProgress:el('stageProgress'),stageFill:el('stageFill'),bossHud:el('bossHud'),bossName:el('bossName'),bossHealth:el('bossHealth'),bossPhase:el('bossPhase'),announce:el('announce'),announceTitle:el('announceTitle'),announceText:el('announceText'),difficulty:el('difficulty'),sound:el('sound'),missionStats:el('missionStats')};
const pilot=new Image();pilot.src='pilot-v2.png';
const face=new Image();face.src='face.jpg';
const nebula=new Image();nebula.src='nebula-v2.png';
const alienAtlas=new Image();alienAtlas.src='aliens-v2.png';
const TAU=Math.PI*2,MAX_POWER=3,PLAYER_RADIUS=14;
let runMode='campaign',selectedMission=profile.state.selected,mission=campaign.mission(selectedMission),world=campaign.worlds[mission.world];
let missionDamage=0,salvageTaken=0,eliteKills=0,shotsFired=0,hitsLanded=0,runFinished=false,special=100,lastDrone=-1,formationTime=1.5,formationIndex=0,stormClock=12,stormWarnings=[],resultSuccess=false,lastReward=null;
function waveDuration(){return runMode==='endless'?Math.min(110,54+Math.floor((level-1)/5)*7):mission.duration}
function maxLives(){return difficulties[difficulty].lives+Math.floor(profile.state.upgrades.hull/2)+(profile.state.ship==='bastion'?1:0)}
function changeMission(id){mission=campaign.mission(id);world=campaign.worlds[mission.world]}

const stats={
 laser:{name:'ФОТОННЫЙ ЛАЗЕР',short:'ЛАЗЕР',icon:'✦',c:'#68e9ff',cool:.15,speed:1050,dmg:1.2,r:4},
 spread:{name:'ВЕЕР «ИСКРА»',short:'ВЕЕР',icon:'⋔',c:'#87ffb0',cool:.28,speed:860,dmg:1,r:4},
 plasma:{name:'ПЛАЗМЕННАЯ ПУШКА',short:'ПЛАЗМА',icon:'◉',c:'#cf86ff',cool:.47,speed:640,dmg:4.3,r:12},
 rockets:{name:'САМОНАВОДЯЩИЕСЯ РАКЕТЫ',short:'РАКЕТЫ',icon:'▲',c:'#ffb867',cool:.62,speed:490,dmg:3.6,r:7},
 beam:{name:'ИОННЫЙ ЛУЧ',short:'ЛУЧ',icon:'ϟ',c:'#fff29b',cool:.105,speed:1700,dmg:1.1,r:7}
};
const enemyTypes={
 scout:{name:'Разведчик',r:21,hp:2.1,speed:112,points:90,fire:2.9,c:'#70e5ff',sprite:0},
 interceptor:{name:'Перехватчик',r:25,hp:3.7,speed:91,points:140,fire:2.45,c:'#c795ff',sprite:1},
 armored:{name:'Броненосец',r:33,hp:8.4,speed:57,points:230,fire:3.35,c:'#ffb55b',sprite:2},
 weaver:{name:'Маневренный охотник',r:24,hp:4.1,speed:102,points:170,fire:2.8,c:'#8cf5a6',sprite:3},
 carrier:{name:'Носитель',r:39,hp:11.4,speed:52,points:310,fire:3.3,c:'#ff7eaa',sprite:5}
};
const difficulties={easy:{lives:5,speed:.82,fire:.8,spawn:1.12,boss:.8,label:'Лёгкий'},normal:{lives:4,speed:1,fire:1,spawn:1,boss:1,label:'Обычный'},hard:{lives:3,speed:1.18,fire:1.2,spawn:.86,boss:1.22,label:'Сложный'}};
const originalBosses=[{name:'СТРАЖ «ОРИОН»',title:'Страж Орион',c:'#9a8dff',r:62,hp:92,kind:'guardian',patterns:['fan','aim','fan'],sprite:1},{name:'ДРЕДНОУТ «ТИТАН»',title:'Дредноут Титан',c:'#ffa86c',r:74,hp:128,kind:'dreadnought',patterns:['ring','lanes','aim'],sprite:4},{name:'УЛЕЙ «НЕМЕЗИДА»',title:'Улей Немезида',c:'#f77bba',r:80,hp:154,kind:'mothership',patterns:['lanes','spiral','fan','aim'],sprite:5}];
const bosses=campaign.bossTypes;

let W=innerWidth,H=innerHeight,D=Math.min(2,devicePixelRatio||1),player=null,target={x:0,y:0};
let running=false,paused=false,last=performance.now(),gameTime=0,score=0,lives=4,level=1,weapon='laser',lastShot=-1,spawn=.7,stageTime=0,stageMode='wave',boss=null,intermission=0,announceTime=0,shake=0;
let stars=[],shots=[],enemies=[],hostileShots=[],pickups=[],parts=[],floaters=[],rings=[],hazards=[];
let inventory={laser:1,spread:0,plasma:0,rockets:0,beam:0},guaranteed=new Set(),difficulty='normal',best=0;
let killed=0,bossesKilled=0,pickupsCollected=0;
let movePointerId=null,moveStart=null,playerStart=null;const fireTouches=new Set(),keys=new Set();
let soundOn=profile.state.settings.sound,audioContext=null,lastSound=-1,musicNext=0,musicNote=0;
try{best=Math.max(0,Number(localStorage.getItem('imranMeteorBest2'))||0);if(!localStorage.getItem(campaign.key)){const saved=localStorage.getItem('imranFleetDifficulty');if(difficulties[saved])profile.setting('difficulty',saved);}difficulty=profile.state.settings.difficulty;}catch(error){}
function rnd(a,b){return a+Math.random()*(b-a)}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function playerBounds(){return {left:34,right:Math.max(34,W-34),top:H<=500?105:Math.max(260,H*.3),bottom:Math.max(150,H-130)}}
function resize(){W=innerWidth;H=innerHeight;D=Math.min(2,devicePixelRatio||1);c.width=Math.max(1,Math.floor(W*D));c.height=Math.max(1,Math.floor(H*D));c.style.width=W+'px';c.style.height=H+'px';x.setTransform(D,0,0,D,0,0);if(player){const b=playerBounds();player.x=clamp(player.x,b.left,b.right);player.y=clamp(player.y,b.top,b.bottom);clearInput()}for(const s of stars){s.x=clamp(s.x,0,W);s.y=clamp(s.y,-10,H)}}
addEventListener('resize',resize,{passive:true});
function reset(){score=0;difficulty=profile.state.settings.difficulty;lives=maxLives();level=runMode==='endless'?1:selectedMission;changeMission(level);missionDamage=0;salvageTaken=0;eliteKills=0;shotsFired=0;hitsLanded=0;runFinished=false;special=100;lastDrone=-1;formationTime=1.5;formationIndex=0;stormClock=12;stormWarnings=[];resultSuccess=false;lastReward=null;gameTime=0;stageTime=0;stageMode='wave';boss=null;intermission=0;lastShot=-1;spawn=.8;shake=0;killed=0;bossesKilled=0;pickupsCollected=0;shots=[];enemies=[];hostileShots=[];pickups=[];parts=[];floaters=[];rings=[];hazards=[];guaranteed=new Set();inventory=Object.fromEntries(Object.keys(stats).map(k=>[k,profile.state.arsenal[k]?1:0]));stars=Array.from({length:110},()=>({x:Math.random()*W,y:Math.random()*H,z:rnd(.25,1),tw:rnd(0,TAU)}));const b=playerBounds();player={x:W*.5,y:clamp(H*.75,b.top,b.bottom),vx:0,vy:0,inv:1.6,shield:profile.state.upgrades.shield*1.8+(profile.state.ship==='bastion'?4:0)};target={x:player.x,y:player.y};clearInput();weapon='laser';updateUI();announce(runMode==='endless'?'БЕСКОНЕЧНЫЙ ПОЛЁТ':mission.name.toUpperCase(),runMode==='endless'?'Нарастающие волны. Каждый босс открывает новый рубеж.':campaign.goalText(mission)+' · победи командира',2.7)}
function setText(element,text){if(element&&element.textContent!==String(text))element.textContent=text}
function updateUI(){setText(ui.score,Math.floor(score));setText(ui.lives,lives);if(ui.lives)ui.lives.setAttribute('aria-label','Жизни: '+lives);setText(ui.level,level);setText(ui.best,best);setText(ui.weaponName,stats[weapon].name);setText(ui.weaponPower,'МОЩНОСТЬ '+inventory[weapon]+' / '+MAX_POWER);setText(ui.stageName,runMode==='endless'?'ВОЛНА '+level+' / '+world.name.toUpperCase():mission.name.toUpperCase());setText(el('objectiveText'),runMode==='endless'?'Бесконечный рубеж':campaign.goalText(mission));setText(el('objectiveCount'),runMode==='endless'?world.code:(mission.objective==='salvage'?salvageTaken:mission.objective==='elite'?eliteKills:killed)+' / '+mission.target);setText(el('specialCharge'),Math.floor(special)+'%');setText(el('fireLabel'),profile.state.settings.autoFire?'ИМПУЛЬС':'ОГОНЬ');ui.fire.disabled=profile.state.settings.autoFire&&special<100;ui.fire.setAttribute('aria-label',profile.state.settings.autoFire?'Защитный импульс, заряд '+Math.floor(special)+' процентов':'Огонь, удерживай для стрельбы');const progress=stageMode==='wave'?Math.min(100,stageTime/waveDuration()*100):100;setText(ui.stageProgress,stageMode==='wave'?Math.max(0,Math.ceil(waveDuration()-stageTime))+' с до босса':stageMode==='boss'?'КОМАНДИР ФЛОТА':'СЕКТОР ОЧИЩЕН');if(ui.stageFill)ui.stageFill.style.width=progress+'%';if(ui.bossHud)ui.bossHud.classList.toggle('hidden',!boss||!running);if(boss){setText(ui.bossName,boss.name);if(ui.bossHealth)ui.bossHealth.style.width=Math.max(0,boss.hp/boss.maxHp*100)+'%';setText(ui.bossPhase,boss.warning?'ЗАРЯЖАЕТ АТАКУ':boss.phase===2?'ФАЗА 2 · ЯРОСТЬ':'ФАЗА 1 · ЩИТЫ');}for(const button of document.querySelectorAll('.weapon')){const w=button.dataset.w,power=inventory[w]||0;button.classList.toggle('locked',!power);button.classList.toggle('active',weapon===w);button.disabled=!power;button.setAttribute('aria-disabled',String(!power));button.setAttribute('aria-pressed',String(weapon===w));button.dataset.power=String(power);button.setAttribute('aria-label',stats[w].name+(power?', мощность '+power:' — найди капсулу в полёте'));button.title=power?stats[w].name+' · уровень '+power:'Поймай капсулу '+(stats[w]?stats[w].short:w);const badge=button.querySelector('.weapon-level');if(badge)setText(badge,power?'LV '+power:'С НЕБА')}}
function announce(title,text,time=2.6){setText(ui.announceTitle,title);setText(ui.announceText,text);announceTime=time;if(ui.announce){ui.announce.classList.remove('hidden');ui.announce.classList.add('show')}}
function startGame(){ui.hint.classList.remove('fade','fading');el('pauseMenu').classList.add('hidden');resize();running=true;paused=false;reset();last=performance.now();ui.start.classList.add('hidden');ui.over.classList.add('hidden');[ui.top,ui.weapons,ui.hint,ui.fire,ui.pause].forEach(e=>{if(e)e.classList.remove('hidden')});ui.pause.textContent='⏸';ui.pause.setAttribute('aria-label','Пауза');setText(el('controlHint'),profile.state.settings.autoFire?'Веди ракету пальцем. Нажми ИМПУЛЬС для защиты.':'Веди ракету пальцем. Вторым удерживай ОГОНЬ.');ensureAudio();if(audioContext&&soundOn)audioContext.resume().catch(()=>{});}
function saveBest(){if(score>best){best=Math.floor(score);try{localStorage.setItem('imranMeteorBest2',String(best))}catch(error){}}}
function endGame(success=false){if(!running||runFinished)return;runFinished=true;resultSuccess=success;if(success&&runMode==='campaign')lastReward=profile.award(level,{score,kills:killed,salvage:salvageTaken,elites:eliteKills,damage:missionDamage});else if(runMode==='endless')lastReward={credits:profile.awardEndless(score,killed)};running=false;paused=false;clearInput();saveBest();setText(ui.final,Math.floor(score));setText(ui.finalBest,best);if(ui.missionStats){ui.missionStats.innerHTML='';for(const [value,label] of [[killed,'кораблей'],[bossesKilled,'боссов'],[pickupsCollected,'капсул']]){const item=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=value;span.textContent=label;item.append(strong,span);ui.missionStats.append(item)}}[ui.top,ui.weapons,ui.hint,ui.fire,ui.pause].forEach(e=>{if(e)e.classList.add('hidden')});el('pauseMenu').classList.add('hidden');setText(el('resultTitle'),success?(level===30?'Галактика защищена':'Миссия выполнена'):'Ракета потеряна');setText(el('resultCopy'),success?mission.name+' · '+world.name:'Улучшения и найденное оружие сохранены. Новый вылет — новая попытка.');setText(el('resultMedals'),success?'◆'.repeat(lastReward?.stars||1)+'◇'.repeat(3-(lastReward?.stars||1)):'');setText(el('missionReward'),lastReward?'+'+lastReward.credits+' ◈ СПЛАВА':'Победи командира, чтобы получить награду.');el('nextMission').classList.toggle('hidden',!success||level===30);setText(el('nextMission'),'СЛЕДУЮЩАЯ МИССИЯ ↗');document.dispatchEvent(new CustomEvent('imran:progress'));ui.over.classList.remove('hidden');if(ui.bossHud)ui.bossHud.classList.add('hidden');if(ui.announce){ui.announce.classList.add('hidden');ui.announce.classList.remove('show')}}
function setWeapon(w){if(!stats[w]||!inventory[w])return false;weapon=w;updateUI();return true}
function pulseSound(freq=440,duration=.09,type='sine',volume=.05){if(!soundOn||!audioContext||gameTime-lastSound<.06)return;lastSound=gameTime;try{const osc=audioContext.createOscillator(),gain=audioContext.createGain(),time=audioContext.currentTime;osc.type=type;osc.frequency.setValueAtTime(freq,time);osc.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.55),time+duration);gain.gain.setValueAtTime(volume,time);gain.gain.exponentialRampToValueAtTime(.001,time+duration);osc.connect(gain);gain.connect(audioContext.destination);osc.start(time);osc.stop(time+duration)}catch(error){}}
function shoot(){if(!player||!running||paused)return false;const s=stats[weapon],power=inventory[weapon];if(gameTime-lastShot<s.cool*(1-.06*(power-1)))return false;lastShot=gameTime;shotsFired++;const py=player.y-65,px=player.x;function add(angle=0,offset=0,options={}){shots.push({x:px+offset,y:py,vx:Math.sin(angle)*s.speed,vy:-Math.cos(angle)*s.speed,r:s.r,d:s.dmg*(1+.3*(power-1))*(1+profile.state.upgrades.reactor*.08),t:weapon,life:2.2,angle,trail:[],pierce:weapon==='beam'?3:1,hit:new Set(),...options})}if(weapon==='laser'){if(power===1)add();else if(power===2){add(0,-11);add(0,11)}else{add(0,-14);add(0,14);add(0,0,{d:s.dmg*.9*(1+.3*(power-1))*(1+profile.state.upgrades.reactor*.08)})}}else if(weapon==='spread'){const n=3+(power-1)*2;for(let i=0;i<n;i++)add((i-(n-1)/2)*.14)}else if(weapon==='rockets'){const n=power===3?3:2;for(let i=0;i<n;i++)add((i-(n-1)/2)*.14,(i-(n-1)/2)*18,{speed:s.speed})}else if(weapon==='beam'){add(0,0,{r:7+power*2,d:s.dmg*(1+.4*(power-1))*(1+profile.state.upgrades.reactor*.08),pierce:3+power,len:94})}else add(0,0,{blast:88+power*14});rings.push({x:px,y:py,r:3,max:17,life:.12,total:.12,c:s.c});pulseSound(weapon==='plasma'?220:weapon==='rockets'?135:weapon==='beam'?660:880,.07,'triangle',.025);return true}
function createEnemy(type='scout',elite=false){if(!enemyTypes[type])type='scout';const cfg=enemyTypes[type],scale=(1+mission.world*.18+mission.slot*.07+Math.max(0,level-30)*.025)*(elite?1.65:1),px=rnd(cfg.r+12,Math.max(cfg.r+13,W-cfg.r-12));const enemy={type,name:cfg.name,x:px,y:-cfg.r-35,baseX:px,r:cfg.r,hp:cfg.hp*scale,maxHp:cfg.hp*scale,vx:rnd(-15,15),vy:cfg.speed*difficulties[difficulty].speed*(1+mission.world*.06+mission.slot*.02),age:0,phase:rnd(0,TAU),fire:cfg.fire*rnd(.65,1.3),points:Math.round(cfg.points*(1+.05*(level-1))*(elite?2:1)),elite,dead:false,hit:0,c:cfg.c};enemies.push(enemy);return enemy}
function chooseEnemy(){const n=Math.random();if(stageTime<6)return n<.78?'scout':'interceptor';if(mission.world===0)return n<.32?'scout':n<.6?'interceptor':n<.8?'weaver':n<.97?'armored':'carrier';return n<.2?'scout':n<.42?'interceptor':n<.65?'weaver':n<.85?'armored':'carrier'}
function fireHostile(px,py,angle,speed=170,r=5,c='#ff818a',kind='bolt'){hostileShots.push({x:px,y:py,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,r,c,t:kind,life:8})}
function enemyAttack(enemy){if(!player)return;const aim=Math.atan2(player.y+10-enemy.y,player.x-enemy.x),speed=(145+Math.min(level,30)*2.1)*difficulties[difficulty].speed;if(enemy.type==='scout')fireHostile(enemy.x,enemy.y+15,Math.PI/2,speed,4,'#7df0ff');else if(enemy.type==='interceptor'){fireHostile(enemy.x-14,enemy.y+8,aim-.07,speed+17,5,enemy.c);fireHostile(enemy.x+14,enemy.y+8,aim+.07,speed+17,5,enemy.c)}else if(enemy.type==='armored'){for(let i=-1;i<=1;i++)fireHostile(enemy.x,enemy.y+24,Math.PI/2+i*.24,speed,6,enemy.c)}else if(enemy.type==='weaver'){fireHostile(enemy.x,enemy.y+16,aim,speed+24,5,enemy.c)}else{for(let i=-2;i<=2;i++)fireHostile(enemy.x+i*10,enemy.y+22,Math.PI/2+i*.18,speed,5,enemy.c)}rings.push({x:enemy.x,y:enemy.y+14,r:2,max:18,life:.16,total:.16,c:enemy.c})}
function createPickup(type,px,py){const q={type,x:clamp(px,28,W-28),y:py,vy:145,phase:rnd(0,TAU),r:20,life:15};pickups.push(q);return q}
function unlockedTier(){return level>=11?['laser','spread','plasma','rockets','beam']:level>=6?['laser','spread','plasma','rockets']:stageTime>=18?['laser','spread','plasma']:['laser','spread']}
function dropReward(px,py,guaranteeWeapon=false){const tier=unlockedTier(),missing=tier.filter(w=>!inventory[w]),upgrades=tier.filter(w=>inventory[w]<MAX_POWER);let type;if(guaranteeWeapon)type=missing.length?missing[0]:upgrades[Math.floor(Math.random()*upgrades.length)]||tier[Math.floor(Math.random()*tier.length)];else{const n=Math.random();type=n<.16?'heart':n<.35?'shield':missing.length&&n<.76?missing[0]:tier[Math.floor(Math.random()*tier.length)]}return createPickup(type,px,py)}
function collectPickup(q){if(!q||q.collected)return false;q.collected=true;pickupsCollected++;const type=q.type;if(stats[type]){profile.unlockWeapon(type);const previous=inventory[type];inventory[type]=Math.min(MAX_POWER,previous+1);setWeapon(type);announce(previous===0?'НОВОЕ ОРУЖИЕ: '+stats[type].short:previous<MAX_POWER?stats[type].short+' · МОЩНОСТЬ '+inventory[type]:'МАКСИМАЛЬНАЯ МОЩНОСТЬ',previous===0?'Капсула подобрана — оружие уже в руках!':previous<MAX_POWER?'Повторная капсула усиливает стрельбу':'Бонус +300 очков',2.5);score+=previous===MAX_POWER?300:150;label(q.x,q.y,previous?'LV '+inventory[type]:'НОВОЕ!',stats[type].c)}else if(type==='shield'){player.shield=Math.min(20,player.shield+8+profile.state.upgrades.shield);label(q.x,q.y,'ЩИТ · 8 С','#73ddff');announce('ЭНЕРГОЩИТ ВКЛЮЧЁН','Защита от кораблей и их выстрелов',1.9)}else if(type==='heart'){const previous=lives;lives=Math.min(maxLives(),lives+1);label(q.x,q.y,previous===lives?'+250':'♥ +1','#ff9ba4');if(previous===lives)score+=250}else if(type==='salvage'){salvageTaken++;score+=35;label(q.x,q.y,'+1 СПЛАВ','#eac78b')}else score+=200;boom(q.x,q.y,14,stats[type]?stats[type].c:'#9cf8ff',.55);pulseSound(920,.18,'sine',.08);updateUI();return true}
function damageEnemy(enemy,amount){if(!enemy||enemy.dead||enemy.hp<=0)return false;enemy.hp-=amount;enemy.hit=.13;if(enemy.hp<=0){enemy.dead=true;killed++;if(enemy.elite)eliteKills++;score+=enemy.points;if(Math.random()<.26)createPickup('salvage',enemy.x,enemy.y);boom(enemy.x,enemy.y,18+(enemy.r>30?9:0),enemy.c);rings.push({x:enemy.x,y:enemy.y,r:8,max:enemy.r*2.3,life:.34,total:.34,c:enemy.c});label(enemy.x,enemy.y,'+'+enemy.points,enemy.c);if(Math.random()<.19)dropReward(enemy.x,enemy.y);pulseSound(85,.12,'sawtooth',.05)}return true}
function damagePlayer(){if(!player||!running||player.inv>0)return false;if(player.shield>0){player.inv=.12;rings.push({x:player.x,y:player.y+10,r:30,max:70,life:.24,total:.24,c:'#73efff'});pulseSound(350,.08,'sine',.03);return false}lives--;missionDamage++;document.dispatchEvent(new CustomEvent('imran:haptic',{detail:{kind:'damage'}}));player.inv=1.6;shake=profile.state.settings.reducedMotion?0:.28;boom(player.x,player.y,23,'#ffac73');label(player.x,player.y-45,'♥ −1','#ff9c9c');hostileShots=hostileShots.filter(s=>Math.hypot(s.x-player.x,s.y-player.y)>86);pulseSound(75,.24,'sawtooth',.07);updateUI();if(lives<=0)endGame();return true}
function bossFlightY(){return H<=500?H*.35:Math.max(H*.24,185+boss.r*1.35)}
function beginBoss(){if(stageMode!=='wave'||boss)return;stageMode='boss';const cfg=bosses[mission.boss],scale=1+mission.slot*.13+Math.max(0,level-30)*.022,maxHp=Math.round(cfg.hp*scale*difficulties[difficulty].boss);for(const enemy of enemies)boom(enemy.x,enemy.y,5,'#70c4ff',.45);enemies=[];hostileShots=[];hazards=[];boss={...cfg,r:Math.min(cfg.r,H<=500?52:Math.max(42,(H-370)/3.4)),x:W/2,y:-120,entry:1.6,age:0,hp:maxHp,maxHp,phase:1,fire:2.1,cycle:0,warning:null,hit:0,dead:false};announce('ВНИМАНИЕ: '+cfg.title.toUpperCase(),'Уворачивайся от подсвеченных атак и пробей броню',3.3);pulseSound(120,.35,'sawtooth',.07);updateUI()}
function damageBoss(amount){if(!boss||boss.dead)return false;boss.hp-=amount;boss.hit=.11;if(boss.hp<=0){defeatBoss();return true}if(boss.phase===1&&boss.hp<=boss.maxHp*.5){boss.phase=2;boss.fire=Math.min(boss.fire,1.5);rings.push({x:boss.x,y:boss.y,r:15,max:boss.r*2.5,life:.6,total:.6,c:boss.c});announce('БОСС: ВТОРАЯ ФАЗА','Командир пришёл в ярость — атаки стали быстрее',2.5)}return true}
function defeatBoss(){if(!boss||boss.dead)return false;boss.dead=true;const px=boss.x,py=boss.y,reward=1400+level*220;score+=reward;bossesKilled++;boom(px,py,68,boss.c);boom(px,py,40,'#fff0b7');rings.push({x:px,y:py,r:10,max:Math.min(W*.85,260),life:1.1,total:1.1,c:boss.c});label(px,py,'БОСС +'+reward,'#fff2a1');shake=.45;boss=null;hostileShots=[];enemies=[];hazards=[];stormWarnings=[];if(runMode==='campaign'){endGame(true);return true}stageMode='intermission';intermission=3.4;dropReward(clamp(px-34,25,W-25),py,true);if(lives<maxLives())createPickup('heart',clamp(px+34,25,W-25),py);announce('СЕКТОР '+level+' ОЧИЩЕН!','Подбери награду. Впереди следующий флот!',3);pulseSound(600,.3,'triangle',.08);updateUI();return true}
function beginNextStage(){level++;changeMission((level-1)%30+1);formationTime=1.5;formationIndex=0;stormClock=12;stageTime=0;stageMode='wave';spawn=1;guaranteed=new Set();player.inv=Math.max(player.inv,1.4);announce('СЕКТОР '+level+' · '+world.name.toUpperCase(),'Новые корабли, оружие и командир флота',3);updateUI()}
function bossWarning(){if(!boss)return;const kind=boss.patterns[boss.cycle%boss.patterns.length];boss.cycle++;const lanes=[clamp(player.x,35,W-35)];if(boss.phase===2||boss.kind==='mothership')lanes.push(clamp(player.x+(player.x<W/2?94:-94),35,W-35));boss.warning={kind,time:boss.phase===2?.74:.94,total:boss.phase===2?.74:.94,targetX:player.x,targetY:player.y+10,lanes};}
function bossAttack(){if(!boss||!boss.warning)return;const b=boss,w=b.warning,speed=(148+Math.min(level,30)*2.4)*difficulties[difficulty].speed,aim=Math.atan2(w.targetY-b.y,w.targetX-b.x);if(w.kind==='fan'){const n=b.phase===2?9:7;for(let i=0;i<n;i++)fireHostile(b.x,b.y+b.r*.5,Math.PI/2+(i-(n-1)/2)*.17,speed,6,b.c,'orb')}else if(w.kind==='aim'){for(let i=-1;i<=1;i++)fireHostile(b.x,b.y+18,aim+i*(b.phase===2?.14:.11),speed+45,7,'#fff19b','orb');if(b.phase===2){fireHostile(b.x-b.r*.6,b.y+20,aim,speed+20,6,b.c);fireHostile(b.x+b.r*.6,b.y+20,aim,speed+20,6,b.c)}}else if(w.kind==='ring'){const n=b.phase===2?15:11;for(let i=0;i<n;i++)fireHostile(b.x,b.y+16,.14+Math.PI/(n-1)*i,speed*.86,6,b.c,'orb')}else if(w.kind==='minions'){for(let i=0;i<3&&enemies.length<6;i++){const e=createEnemy(i===1?'armored':'interceptor',b.phase===2&&i===1);e.x=W*(.25+i*.25);e.baseX=e.x;e.y=b.y+30;e.vy*=.72}}else if(w.kind==='cross'){const n=b.phase===2?11:7;for(let i=0;i<n;i++){fireHostile(b.x-b.r*.6,b.y+25,Math.PI/2+(i-(n-1)/2)*.14,speed,5,b.c);fireHostile(b.x+b.r*.6,b.y+25,Math.PI/2-(i-(n-1)/2)*.14,speed,5,b.c)}}else if(w.kind==='lanes'){for(const lane of w.lanes)hazards.push({x:lane,y:b.y+b.r*.55,w:b.phase===2?28:24,life:.6,total:.6,c:b.c})}else{const n=b.phase===2?13:9;for(let i=0;i<n;i++)fireHostile(b.x,b.y+20,Math.PI/2+(i-(n-1)/2)*.15+Math.sin(b.age)*.16,speed*(.76+i*.026),5,b.c,'orb')}rings.push({x:b.x,y:b.y+22,r:5,max:b.r*.8,life:.22,total:.22,c:b.c});b.warning=null;b.fire=Math.max(1.2,(b.phase===2?1.65:2.4)-(level-1)*.045)/difficulties[difficulty].fire;pulseSound(170,.19,'triangle',.05)}
function boom(px,py,count=18,color='#ffad6c',scale=1){const remaining=Math.max(0,260-parts.length);for(let i=0;i<Math.min(count,remaining);i++){const angle=rnd(0,TAU),speed=rnd(45,230)*scale,life=rnd(.28,.75);parts.push({x:px,y:py,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,life,total:life,size:rnd(1.7,5.8)*scale,c:color})}}
function label(px,py,text,color='#ffe896'){floaters.push({x:px,y:py,text,c:color,life:1.1})}
function update(dt){if(!running||paused)return;gameTime+=dt;special=Math.min(100,special+dt*6);if(gameTime>5)ui.hint.classList.add('fade');if(gameTime>6)ui.hint.classList.add('hidden');stageTime+=stageMode==='wave'?dt:0;player.inv=Math.max(0,player.inv-dt);player.shield=Math.max(0,player.shield-dt);shake=Math.max(0,shake-dt);announceTime-=dt;if(announceTime<=0&&ui.announce){ui.announce.classList.add('hidden');ui.announce.classList.remove('show')}for(const s of stars){s.y+=(20+110*s.z)*dt;s.tw+=dt;if(s.y>H+5){s.y=-5;s.x=Math.random()*W}}
 const bounds=playerBounds(),dx=Number(keys.has('ArrowRight')||keys.has('KeyD'))-Number(keys.has('ArrowLeft')||keys.has('KeyA')),dy=Number(keys.has('ArrowDown')||keys.has('KeyS'))-Number(keys.has('ArrowUp')||keys.has('KeyW'));if(dx||dy){const step=350*dt*(profile.state.ship==='swift'?1.25:profile.state.ship==='bastion'?.88:1)/(Math.hypot(dx,dy)||1);target.x=clamp(target.x+dx*step,bounds.left,bounds.right);target.y=clamp(target.y+dy*step,bounds.top,bounds.bottom)}const follow=1-Math.exp(-20*dt),oldX=player.x,oldY=player.y;player.x=clamp(player.x+(target.x-player.x)*follow,bounds.left,bounds.right);player.y=clamp(player.y+(target.y-player.y)*follow,bounds.top,bounds.bottom);player.vx=(player.x-oldX)/Math.max(.001,dt);player.vy=(player.y-oldY)/Math.max(.001,dt);if(fireTouches.size||profile.state.settings.autoFire)shoot();updateDrone();
 if(stageMode==='wave'){const scheduled=[[5.8,'spread'],[22,'plasma']];if(level>=6)scheduled.push([9,'rockets']);if(level>=11)scheduled.push([16,'beam']);if(mission.objective==='salvage')scheduled.push([14,'salvage'],[28,'salvage'],[42,'salvage']);for(const [time,type] of scheduled){if(stageTime>=time&&!guaranteed.has(type)){guaranteed.add(type);const q=createPickup(type,player.x,-24);q.vy=Math.max(180,H*.43);if(stats[type]&&!inventory[type])announce('КАПСУЛА '+stats[type].short+' В НЕБЕ','Подлети к ней, чтобы получить новое оружие',2.5)}}if(stageTime>=waveDuration())beginBoss();else{spawn-=dt;formationTime-=dt;if(spawn<=0){if(enemies.length<12)createEnemy(chooseEnemy(),stageTime>14&&Math.random()<mission.eliteRate);spawn=Math.max(.6,mission.spawn)*difficulties[difficulty].spawn*rnd(.85,1.2)}if(formationTime<=0){spawnFormation();formationTime=9.5-mission.world*.5;}updateStorm(dt)}}else if(stageMode==='intermission'){intermission-=dt;if(intermission<=0)beginNextStage()}
 for(const enemy of enemies){if(enemy.dead)continue;enemy.age+=dt;enemy.hit=Math.max(0,enemy.hit-dt);enemy.y+=enemy.vy*dt;if(enemy.type==='interceptor')enemy.x=clamp(enemy.baseX+Math.sin(enemy.age*1.5+enemy.phase)*46,enemy.r,W-enemy.r);else if(enemy.type==='weaver')enemy.x=clamp(enemy.baseX+Math.sin(enemy.age*2.15+enemy.phase)*Math.min(W*.24,90),enemy.r,W-enemy.r);else if(enemy.type==='carrier')enemy.x=clamp(enemy.baseX+Math.sin(enemy.age*.65+enemy.phase)*30,enemy.r,W-enemy.r);else{enemy.x+=enemy.vx*dt;if(enemy.x<enemy.r||enemy.x>W-enemy.r)enemy.vx*=-1}if(enemy.y>35&&enemy.y<H*.67&&gameTime>4){enemy.fire-=dt*difficulties[difficulty].fire;if(enemy.fire<=0){enemyAttack(enemy);enemy.fire=enemyTypes[enemy.type].fire/(1+(level-1)*.055)}}if(enemy.y>H+enemy.r+20)enemy.dead=true;if(!enemy.dead&&Math.hypot(enemy.x-player.x,enemy.y-(player.y+10))<enemy.r*.72+PLAYER_RADIUS){if(damagePlayer()){enemy.dead=true;boom(enemy.x,enemy.y,20,enemy.c)}}}
 if(!running)return;
 if(boss){boss.age+=dt;boss.hit=Math.max(0,boss.hit-dt);if(boss.entry>0){boss.entry=Math.max(0,boss.entry-dt);const progress=1-boss.entry/1.6;boss.y=-120+(bossFlightY()+120)*(1-Math.pow(1-progress,3))}else{boss.y=bossFlightY()+Math.sin(boss.age*1.1)*8;boss.x=W/2+Math.sin(boss.age*.77)*Math.min(W*.25,115);if(boss.warning){boss.warning.time-=dt;if(boss.warning.time<=0)bossAttack()}else{boss.fire-=dt;if(boss.fire<=0)bossWarning()}}if(Math.hypot(boss.x-player.x,boss.y-(player.y+10))<boss.r*.75+PLAYER_RADIUS)damagePlayer()}
 if(!running)return;
 for(const shot of shots){shot.life-=dt;if(shot.t==='rockets'){const choices=enemies.filter(e=>!e.dead&&e.y<shot.y+80);let nearest=boss||null,distance=nearest?Math.hypot(nearest.x-shot.x,nearest.y-shot.y):Infinity;for(const enemy of choices){const d=Math.hypot(enemy.x-shot.x,enemy.y-shot.y);if(d<distance){distance=d;nearest=enemy}}if(nearest){const angle=Math.atan2(nearest.y-shot.y,nearest.x-shot.x),speed=shot.speed;shot.vx+=(Math.cos(angle)*speed-shot.vx)*Math.min(1,dt*3.8);shot.vy+=(Math.sin(angle)*speed-shot.vy)*Math.min(1,dt*3.8)}shot.trail.push({x:shot.x,y:shot.y});if(shot.trail.length>7)shot.trail.shift()}shot.prevX=shot.x;shot.prevY=shot.y;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;}
 for(let i=shots.length-1;i>=0;i--){const shot=shots[i];if(shot.life<=0||shot.y<-120||shot.y>H+80||shot.x<-90||shot.x>W+90){shots.splice(i,1);continue}let collision=null;for(const enemy of enemies){if(enemy.dead||shot.hit.has(enemy))continue;if(segmentDistance(shot.prevX??shot.x,shot.prevY??shot.y,shot.x,shot.y,enemy.x,enemy.y)<shot.r+enemy.r*.82){collision=enemy;break}}const hitBoss=!collision&&boss&&!shot.hit.has(boss)&&segmentDistance(shot.prevX??shot.x,shot.prevY??shot.y,shot.x,shot.y,boss.x,boss.y)<shot.r+boss.r*.78;if(!collision&&!hitBoss)continue;const victim=collision||boss;hitsLanded++;shot.hit.add(victim);if(shot.t==='plasma'){const blast=shot.blast||105;for(const enemy of enemies)if(!enemy.dead&&Math.hypot(enemy.x-shot.x,enemy.y-shot.y)<blast+enemy.r*.3)damageEnemy(enemy,shot.d);if(boss&&Math.hypot(boss.x-shot.x,boss.y-shot.y)<blast+boss.r*.6)damageBoss(shot.d);rings.push({x:shot.x,y:shot.y,r:10,max:blast,life:.38,total:.38,c:stats.plasma.c});boom(shot.x,shot.y,23,stats.plasma.c,.85);shot.pierce=0}else{if(collision)damageEnemy(collision,shot.d);else damageBoss(shot.d);boom(shot.x,shot.y,shot.t==='rockets'?18:4,stats[shot.t].c,shot.t==='rockets'?.85:.45);shot.pierce--}if(shot.pierce<=0)shots.splice(i,1)}
 if(!running)return;
 enemies=enemies.filter(enemy=>!enemy.dead);for(let i=hostileShots.length-1;i>=0;i--){const shot=hostileShots[i];if(!shot)continue;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.life-=dt;if(Math.hypot(shot.x-player.x,shot.y-(player.y+10))<shot.r+PLAYER_RADIUS){damagePlayer();if(!running)return;if(hostileShots[i]===shot)hostileShots.splice(i,1);continue}if(shot.life<=0||shot.y>H+50||shot.y<-90||shot.x<-50||shot.x>W+50)hostileShots.splice(i,1)}
 for(let i=hazards.length-1;i>=0;i--){const hazard=hazards[i];hazard.life-=dt;if(Math.abs(player.x-hazard.x)<hazard.w/2+PLAYER_RADIUS&&player.y+10>hazard.y)damagePlayer();if(hazard.life<=0)hazards.splice(i,1)}
 if(!running)return;
 for(const q of pickups){q.life-=dt;q.phase+=dt*3;q.y+=q.vy*dt;const distance=Math.hypot(q.x-player.x,q.y-(player.y+10));if(distance<102+profile.state.upgrades.magnet*18){q.x+=(player.x-q.x)*Math.min(1,dt*4);q.y+=(player.y+10-q.y)*Math.min(1,dt*3.5)}if(distance<q.r+PLAYER_RADIUS+7)collectPickup(q)}pickups=pickups.filter(q=>!q.collected&&q.life>0&&q.y<H+50);for(const p of parts){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=Math.exp(-2.2*dt);p.vy*=Math.exp(-2.2*dt);p.life-=dt}parts=parts.filter(p=>p.life>0);for(const ring of rings){ring.life-=dt;ring.r+=(ring.max-ring.r)*Math.min(1,dt*10)}rings=rings.filter(r=>r.life>0);for(const f of floaters){f.y-=35*dt;f.life-=dt}floaters=floaters.filter(f=>f.life>0);updateUI();}
function circle(px,py,r,color){x.fillStyle=color;x.beginPath();x.arc(px,py,Math.max(0,r),0,TAU);x.fill()}
function poly(points,fill,stroke,width=1){x.beginPath();points.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.closePath();if(fill){x.fillStyle=fill;x.fill()}if(stroke){x.strokeStyle=stroke;x.lineWidth=width;x.stroke()}}
function glow(px,py,r,color,alpha=.2){x.save();x.globalAlpha=alpha;x.shadowColor=color;x.shadowBlur=r*.75;circle(px,py,r*.38,color);x.restore()}
function planet(px,py,r){x.save();x.globalAlpha=.67;const g=x.createRadialGradient(px-r*.55,py-r*.6,r*.1,px,py,r);g.addColorStop(0,world.planet[0]);g.addColorStop(.55,world.planet[1]);g.addColorStop(1,world.planet[2]);circle(px,py,r,g);x.strokeStyle='rgba(122,182,240,.32)';x.lineWidth=1;x.beginPath();x.arc(px,py,r+3,0,TAU);x.stroke();x.globalAlpha=.14;x.strokeStyle='#96a3e2';x.lineWidth=r*.13;x.beginPath();x.ellipse(px,py,r*1.65,r*.3,-.28,0,TAU);x.stroke();x.restore()}
function drawBackground(){x.fillStyle='#03071c';x.fillRect(0,0,W,H);if(nebula.complete&&nebula.naturalWidth){const scale=Math.max(W/nebula.naturalWidth,H/nebula.naturalHeight)*1.08,iw=nebula.naturalWidth*scale,ih=nebula.naturalHeight*scale,offset=Math.sin(gameTime*.028)*Math.min(20,(ih-H)*.4);x.drawImage(nebula,(W-iw)/2,(H-ih)/2+offset,iw,ih);x.fillStyle='rgba(3,7,25,.3)';x.fillRect(0,0,W,H)}else{const g=x.createLinearGradient(0,0,W,H);g.addColorStop(0,'#090a28');g.addColorStop(.45,'#112754');g.addColorStop(1,'#03091c');x.fillStyle=g;x.fillRect(0,0,W,H);x.save();x.globalAlpha=.23;x.fillStyle='#6949cf';x.beginPath();x.ellipse(W*.22,H*.34,W*.65,H*.1,-.4,0,TAU);x.fill();x.globalAlpha=.13;x.fillStyle='#24a0cd';x.beginPath();x.ellipse(W*.8,H*.68,W*.55,H*.11,-.4,0,TAU);x.fill();x.restore()}x.fillStyle=world.shade;x.fillRect(0,0,W,H);drawWorldDetails();planet(W*.92,H*.31,Math.min(W,H)*.17);for(const s of stars){const size=.5+s.z*1.2;x.globalAlpha=.23+s.z*.6+Math.sin(s.tw)*.08;x.fillStyle=s.z>.8?'#d9f4ff':'#9baada';x.fillRect(s.x,s.y,size,size+(running&&!paused?s.z*2.4:0))}x.globalAlpha=1;const shade=x.createLinearGradient(0,H*.65,0,H);shade.addColorStop(0,'rgba(2,7,22,0)');shade.addColorStop(1,'rgba(2,7,22,.65)');x.fillStyle=shade;x.fillRect(0,H*.65,W,H*.35)}
function atlasShip(index,size){if(!alienAtlas.complete||!alienAtlas.naturalWidth)return false;const cellW=alienAtlas.naturalWidth/3,cellH=alienAtlas.naturalHeight/2;x.drawImage(alienAtlas,(index%3)*cellW,Math.floor(index/3)*cellH,cellW,cellH,-size/2,-size/2,size,size);return true}
function ship(enemy){x.save();x.translate(enemy.x,enemy.y);x.rotate(enemy.type==='weaver'?Math.cos(enemy.age*2.15+enemy.phase)*.15:Math.sin(enemy.age)*.025);const r=enemy.r,color=enemy.c;glow(0,-r*.3,r*1.2,color,.23);if(!atlasShip(enemyTypes[enemy.type].sprite,r*2.65)){const metal=x.createLinearGradient(0,-r,0,r);metal.addColorStop(0,'#b4c6de');metal.addColorStop(.35,'#34415f');metal.addColorStop(.7,'#14213d');metal.addColorStop(1,'#8493b3');if(enemy.type==='scout'){poly([[-r,-r*.22],[-r*.28,-r*.55],[0,-r*.85],[r*.28,-r*.55],[r,-r*.22],[r*.78,r*.42],[r*.25,r*.22],[0,r],[-r*.25,r*.22],[-r*.78,r*.42]],metal,'#92c5e6',1);poly([[-r*.18,-r*.38],[r*.18,-r*.38],[r*.28,r*.38],[0,r*.7],[-r*.28,r*.38]],'#071b32',color,1.4)}else if(enemy.type==='interceptor'||enemy.type==='weaver'){poly([[-r*1.2,-r*.55],[-r*.48,-r*.22],[-r*.22,-r*.85],[r*.22,-r*.85],[r*.48,-r*.22],[r*1.2,-r*.55],[r*.8,r*.7],[r*.22,r*.3],[0,r],[-r*.22,r*.3],[-r*.8,r*.7]],metal,'#9c93c7',1.4);poly([[-r*.15,-r*.4],[r*.15,-r*.4],[r*.24,r*.4],[0,r*.68],[-r*.24,r*.4]],'#332461',color,1.6);circle(-r*.78,r*.28,3,color);circle(r*.78,r*.28,3,color)}else if(enemy.type==='armored'){poly([[-r,-r*.45],[-r*.65,-r*.85],[r*.65,-r*.85],[r,-r*.45],[r*.9,r*.62],[r*.48,r*.85],[-r*.48,r*.85],[-r*.9,r*.62]],metal,'#a2b1bd',1.7);for(const side of [-1,1]){poly([[side*r*.3,-r*.53],[side*r*.8,-r*.35],[side*r*.72,r*.45],[side*r*.32,r*.62]],'#26364a','#7e8b9e',1);x.fillStyle='#0a1222';x.fillRect(side*r*.55-5,r*.48,10,r*.42);circle(side*r*.55,r*.88,4,color)}poly([[-r*.27,-r*.36],[r*.27,-r*.36],[r*.31,r*.16],[0,r*.35],[-r*.31,r*.16]],'#4e351f',color,2)}else{poly([[-r,-r*.52],[-r*.52,-r*.83],[r*.52,-r*.83],[r,-r*.52],[r*1.15,r*.25],[r*.78,r*.63],[r*.3,r*.43],[0,r*.9],[-r*.3,r*.43],[-r*.78,r*.63],[-r*1.15,r*.25]],metal,'#ad93b2',1.5);poly([[-r*.25,-r*.42],[r*.25,-r*.42],[r*.36,r*.38],[0,r*.62],[-r*.36,r*.38]],'#382342',color,1.6);for(let i=-2;i<=2;i++)circle(i*r*.33,r*.27,3.5,color)}}if(enemy.elite){x.strokeStyle='#eed397';x.lineWidth=1.3;x.globalAlpha=.65;x.beginPath();x.arc(0,0,r*1.08,0,TAU);x.stroke();x.globalAlpha=1;x.fillStyle='#f0d397';x.font='700 8px system-ui';x.textAlign='center';x.fillText('ЭЛИТА',0,-r*1.25)}if(enemy.hit>0){x.globalAlpha=.6;circle(0,0,r*.53,'#fff');x.globalAlpha=1}if(enemy.hp<enemy.maxHp){x.fillStyle='#061126';x.fillRect(-r,-r-13,r*2,3);x.fillStyle=color;x.fillRect(-r,-r-13,r*2*Math.max(0,enemy.hp/enemy.maxHp),3)}x.restore()}
function drawBoss(){if(!boss)return;const b=boss,r=b.r;x.save();x.translate(b.x,b.y);const pulse=1+Math.sin(b.age*3)*.1;glow(0,0,r*1.7,b.c,.2);if(!atlasShip(b.sprite,r*2.7)){const metal=x.createLinearGradient(0,-r,0,r);metal.addColorStop(0,'#b5bfd6');metal.addColorStop(.3,'#424f70');metal.addColorStop(.55,'#15223d');metal.addColorStop(1,'#50618b');if(b.kind==='guardian'){poly([[-r*1.3,-r*.4],[-r*.64,-r*.82],[-r*.28,-r*.4],[0,-r],[r*.28,-r*.4],[r*.64,-r*.82],[r*1.3,-r*.4],[r*.96,r*.55],[r*.38,r*.28],[0,r*.78],[-r*.38,r*.28],[-r*.96,r*.55]],metal,'#b4b1dc',2);for(const side of [-1,1]){poly([[side*r*.5,-r*.35],[side*r*1.1,-r*.24],[side*r*.86,r*.36],[side*r*.48,r*.2]],'#202543',b.c,1.5);circle(side*r*.84,r*.33,6,b.c)}}else if(b.kind==='dreadnought'){poly([[-r*1.2,-r*.44],[-r*.72,-r*.87],[r*.72,-r*.87],[r*1.2,-r*.44],[r*1.15,r*.53],[r*.7,r*.75],[-r*.7,r*.75],[-r*1.15,r*.53]],metal,'#c7b294',2.2);for(const side of [-1,1]){poly([[side*r*.48,-r*.57],[side*r*.96,-r*.27],[side*r*.87,r*.54],[side*r*.43,r*.42]],'#303741','#af9787',1.5);x.fillStyle='#061222';x.fillRect(side*r*.68-9,r*.28,18,r*.7);circle(side*r*.68,r*.97,7,b.c)}}else{x.fillStyle=metal;x.beginPath();x.ellipse(0,0,r*1.27,r*.55,0,0,TAU);x.fill();x.strokeStyle='#b7a0c2';x.lineWidth=2;x.stroke();poly([[-r*.7,-r*.13],[-r*.36,-r*.72],[r*.36,-r*.72],[r*.7,-r*.13],[r*.41,r*.32],[-r*.41,r*.32]],'#252039',b.c,2);for(let i=-2;i<=2;i++)circle(i*r*.43,r*.61,5,b.c)}}glow(0,0,r*.45,b.c,.28);if(b.phase===2){x.strokeStyle=b.c;x.lineWidth=1.5;x.globalAlpha=.35;x.beginPath();x.arc(0,0,r*.92*pulse,0,TAU);x.stroke();x.globalAlpha=1}if(b.hit>0){x.globalAlpha=.5;circle(0,0,r*.32,'#fff')}x.restore();if(b.warning)drawWarning(b.warning)}
function drawWarning(w){if(!boss)return;const b=boss,flicker=profile.state.settings.reducedMotion?.25:.25+Math.sin(gameTime*18)*.1;x.save();x.strokeStyle='#ffb677';x.lineWidth=1.5;x.setLineDash([7,9]);x.globalAlpha=.7;if(w.kind==='lanes'){for(const lane of w.lanes){x.fillStyle='rgba(255,113,101,'+flicker+')';x.fillRect(lane-(b.phase===2?28:24),b.y+b.r*.5,b.phase===2?56:48,H-b.y);x.beginPath();x.moveTo(lane,b.y+b.r*.5);x.lineTo(lane,H);x.stroke();circle(lane,H-148,18,'rgba(255,180,112,.5)')}}else if(w.kind==='aim'){const angle=Math.atan2(w.targetY-b.y,w.targetX-b.x);x.beginPath();x.moveTo(b.x,b.y);x.lineTo(b.x+Math.cos(angle)*H*1.4,b.y+Math.sin(angle)*H*1.4);x.stroke();x.beginPath();x.arc(w.targetX,w.targetY,28,0,TAU);x.stroke()}else{const n=w.kind==='ring'?9:5,spread=w.kind==='ring'?1.33:.51;for(let i=0;i<n;i++){const angle=Math.PI/2+(i-(n-1)/2)*spread/((n-1)/2);x.beginPath();x.moveTo(b.x,b.y+20);x.lineTo(b.x+Math.cos(angle)*150,b.y+20+Math.sin(angle)*150);x.stroke()}}x.setLineDash([]);x.globalAlpha=.9;x.strokeStyle='#fff2aa';x.lineWidth=3;x.beginPath();x.arc(b.x,b.y,b.r*.32,-Math.PI/2,-Math.PI/2+TAU*(1-w.time/w.total));x.stroke();x.restore()}
function drawShot(s){x.save();x.translate(s.x,s.y);const color=stats[s.t].c;x.shadowColor=color;x.shadowBlur=s.t==='plasma'?17:10;if(s.t==='laser'){x.strokeStyle=color;x.lineWidth=4;x.beginPath();x.moveTo(0,13);x.lineTo(0,-18);x.stroke();x.strokeStyle='#effeff';x.lineWidth=1.5;x.stroke()}else if(s.t==='beam'){x.strokeStyle='rgba(255,215,88,.23)';x.lineWidth=s.r*2.4;x.beginPath();x.moveTo(0,35);x.lineTo(0,-s.len);x.stroke();x.strokeStyle=color;x.lineWidth=s.r;x.stroke();x.strokeStyle='#fffef2';x.lineWidth=2;x.stroke()}else if(s.t==='rockets'){x.restore();x.save();for(let i=0;i<s.trail.length;i++){x.globalAlpha=i/s.trail.length*.55;circle(s.trail[i].x,s.trail[i].y,1+i*.45,'#ffb460')}x.globalAlpha=1;x.translate(s.x,s.y);x.rotate(Math.atan2(s.vy,s.vx)+Math.PI/2);poly([[-5,8],[-4,-7],[0,-14],[4,-7],[5,8]],'#eff5fb','#ffc383',1);poly([[-6,8],[0,21+Math.sin(gameTime*50)*5],[6,8]],'#ff9b4a');circle(0,-6,2,'#ffba67')}else if(s.t==='plasma'){glow(0,0,s.r*2.8,color,.4);circle(0,0,s.r,color);circle(-3,-3,s.r*.46,'#ffebff');x.strokeStyle='#f8c3ff';x.lineWidth=2;x.beginPath();x.arc(0,0,s.r+5,gameTime*8,gameTime*8+Math.PI*1.3);x.stroke()}else{circle(0,0,s.r,color);circle(0,0,1.8,'#fff')}x.restore()}
function drawPickup(q){const cfg=stats[q.type],color=cfg?cfg.c:q.type==='heart'?'#ff90a4':q.type==='salvage'?'#e7c68d':'#78e6ff';x.save();x.translate(q.x,q.y);x.rotate(Math.sin(q.phase)*.07);glow(0,0,54,color,.32);x.strokeStyle='rgba(255,255,255,.35)';x.lineWidth=1;x.beginPath();x.moveTo(-11,-q.r-8);x.lineTo(-6,-q.r-18);x.moveTo(0,-q.r-12);x.lineTo(0,-q.r-27);x.moveTo(11,-q.r-8);x.lineTo(6,-q.r-18);x.stroke();poly([[-21,-15],[-14,-22],[14,-22],[21,-15],[21,15],[14,22],[-14,22],[-21,15]],'#112540',color,2);x.fillStyle=color;x.font='900 24px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(cfg?cfg.icon:q.type==='heart'?'♥':q.type==='salvage'?'◈':'⬡',0,0);if(cfg){x.font='900 9px system-ui';x.fillStyle='#e8f7ff';x.fillText(cfg.short,0,34)}x.restore()}
function drawFallbackPilot(){const rgrad=x.createLinearGradient(-28,0,32,0);rgrad.addColorStop(0,'#88adc4');rgrad.addColorStop(.38,'#f0fbff');rgrad.addColorStop(1,'#7194b4');poly([[0,-34],[19,-5],[26,45],[17,66],[-17,66],[-26,45],[-19,-5]],rgrad,'#bed8ee',1.5);poly([[-22,30],[-44,65],[-21,58]],'#fb6a51','#ffaf6f',1);poly([[22,30],[44,65],[21,58]],'#fb6a51','#ffaf6f',1);poly([[0,-34],[17,-8],[-17,-8]],'#ff8c53');poly([[-19,4],[19,4],[24,22],[-24,22]],'#2679b6');x.fillStyle='#132841';x.fillRect(-15,46,30,9);x.strokeStyle='#ffa58c';x.lineWidth=8;x.beginPath();x.moveTo(-14,-24);x.lineTo(-26,3);x.lineTo(-32,31);x.moveTo(14,-24);x.lineTo(24,-5);x.lineTo(28,23);x.stroke();x.strokeStyle='#3379bf';x.lineWidth=11;x.beginPath();x.moveTo(-11,-42);x.lineTo(-24,-20);x.lineTo(-15,-5);x.moveTo(11,-42);x.lineTo(26,-24);x.lineTo(14,-12);x.stroke();poly([[-17,-54],[17,-54],[19,-22],[-19,-22]],'#448fdb','#91bded',1);x.save();x.beginPath();x.arc(0,-67,22,0,TAU);x.clip();circle(0,-67,22,'#eab7a3');if(face.complete&&face.naturalWidth)x.drawImage(face,-23,-90,46,46);x.restore();x.strokeStyle='#8ceaff';x.lineWidth=1.3;x.beginPath();x.arc(0,-67,23,0,TAU);x.stroke()}
function drawPlayer(){if(!player)return;x.save();x.translate(player.x,player.y);x.rotate(clamp(player.vx/1800,-.13,.13));if(player.inv>0&&!profile.state.settings.reducedMotion)x.globalAlpha=.4+.6*(Math.sin(gameTime*37)*.5+.5);const f=x.createLinearGradient(0,49,0,128);f.addColorStop(0,'#faffea');f.addColorStop(.22,'#91f5ff');f.addColorStop(.55,'#38a8ff');f.addColorStop(1,'rgba(42,94,255,0)');x.fillStyle=f;x.beginPath();x.moveTo(-13,53);x.quadraticCurveTo(-10,90,0,126+Math.sin(gameTime*48)*9);x.quadraticCurveTo(10,90,13,53);x.fill();glow(0,64,55,'#4fdfff',.25);if(pilot.complete&&pilot.naturalWidth){const desiredH=Math.min(154,Math.max(143,H*.175)),scale=Math.min(108/pilot.naturalWidth,desiredH/pilot.naturalHeight),iw=pilot.naturalWidth*scale,ih=pilot.naturalHeight*scale;x.drawImage(pilot,-iw/2,-ih*.57,iw,ih)}else drawFallbackPilot();x.restore();if(player.shield>0){x.save();x.translate(player.x,player.y+10);const pulse=48+Math.sin(gameTime*4)*2;glow(0,0,pulse*1.4,'#73e7ff',.13);x.strokeStyle='rgba(124,238,255,.7)';x.lineWidth=2;x.beginPath();x.ellipse(0,0,pulse,pulse*1.32,0,0,TAU);x.stroke();x.globalAlpha=.45;x.strokeStyle='#c4f6ff';x.lineWidth=4;x.beginPath();x.ellipse(0,0,pulse,pulse*1.32,0,gameTime*1.6,gameTime*1.6+.9);x.stroke();x.restore()}x.save();x.globalAlpha=.45;circle(player.x,player.y+10,2.5,'#e6faff');x.restore()}
function draw(){drawBackground();x.save();if(shake>0&&!paused&&!profile.state.settings.reducedMotion)x.translate(Math.sin(gameTime*120)*shake*6,Math.cos(gameTime*131)*shake*4);for(const q of pickups)drawPickup(q);for(const s of shots)drawShot(s);for(const enemy of enemies)ship(enemy);drawBoss();for(const warning of stormWarnings){x.fillStyle='rgba(125,231,166,.14)';x.fillRect(warning.x-32,170,64,H);x.strokeStyle='#a4efb4';x.setLineDash([8,10]);x.strokeRect(warning.x-32,170,64,H-170);x.setLineDash([])}for(const hazard of hazards){x.save();x.globalAlpha=Math.min(1,hazard.life/.15);const g=x.createLinearGradient(hazard.x-hazard.w,0,hazard.x+hazard.w,0);g.addColorStop(0,'rgba(255,113,146,0)');g.addColorStop(.45,hazard.c);g.addColorStop(.5,'#fff8d5');g.addColorStop(.55,hazard.c);g.addColorStop(1,'rgba(255,113,146,0)');x.fillStyle=g;x.fillRect(hazard.x-hazard.w,hazard.y,hazard.w*2,H-hazard.y);x.restore()}for(const s of hostileShots){x.save();x.shadowColor=s.c;x.shadowBlur=8;circle(s.x,s.y,s.r,s.c);circle(s.x-s.r*.2,s.y-s.r*.2,s.r*.4,'#fffbef');x.restore()}drawPlayer();drawDrone();for(const p of parts){x.globalAlpha=Math.max(0,p.life/p.total);circle(p.x,p.y,p.size,p.c)}x.globalAlpha=1;for(const ring of rings){x.save();x.globalAlpha=ring.life/ring.total*.7;x.strokeStyle=ring.c;x.lineWidth=2;x.beginPath();x.arc(ring.x,ring.y,ring.r,0,TAU);x.stroke();x.restore()}for(const f of floaters){x.save();x.globalAlpha=Math.min(1,f.life*2);x.fillStyle=f.c;x.font='900 15px system-ui';x.textAlign='center';x.shadowColor='#02071a';x.shadowBlur=4;x.fillText(f.text,f.x,f.y);x.restore()}x.restore();if(paused){x.fillStyle='rgba(2,7,23,.72)';x.fillRect(0,0,W,H);}}
function frame(now){const dt=Math.max(0,Math.min(.035,(now-last)/1000||0));last=now;musicTick(now);update(dt);draw();requestAnimationFrame(frame)}

function segmentDistance(ax,ay,bx,by,px,py){const dx=bx-ax,dy=by-ay,length=dx*dx+dy*dy,t=length?clamp(((px-ax)*dx+(py-ay)*dy)/length,0,1):0;return Math.hypot(px-ax-dx*t,py-ay-dy*t)}
function spawnFormation(){formationIndex++;const n=mission.formation==='armada'?5:mission.formation==='siege'?2:3,elite=mission.objective==='elite'&&formationIndex%2===0;for(let i=0;i<n&&enemies.length<14;i++){const type=mission.formation==='siege'?'armored':mission.formation==='crossfire'?'weaver':formationIndex%3===0?'interceptor':'scout',e=createEnemy(type,elite&&i===Math.floor(n/2));if(mission.formation==='wedge'){e.x=W/2+(i-(n-1)/2)*Math.min(72,W*.19);e.y=-45-Math.abs(i-(n-1)/2)*40}else if(mission.formation==='crossfire'){e.x=i%2?W-48:48;e.y=-50-i*75;e.phase=i*Math.PI}else if(mission.formation==='siege'){e.x=W*(.28+i*.44);e.y=-75-i*60}else{e.x=W*(i+1)/(n+1);e.y=-60-(mission.formation==='patrol'?i*55:0)}e.baseX=e.x;e.vx=mission.formation==='patrol'?14:0;}}
function updateStorm(dt){for(const warning of stormWarnings){warning.time-=dt;if(warning.time<=0&&!warning.fired){warning.fired=true;hazards.push({x:warning.x,y:180,w:30,life:.5,total:.5,c:'#aeefae'})}}stormWarnings=stormWarnings.filter(w=>!w.fired);if(world.style!=='storm'||stageTime<10)return;stormClock-=dt;if(stormClock<=0){stormWarnings.push({x:player.x,time:1.5,fired:false});stormClock=13;announce('ИОННЫЙ РАЗРЯД','Покинь подсвеченный коридор',1.3)}}
function activateSpecial(){if(!running||paused||special<100)return false;special=0;hostileShots=[];hazards=[];stormWarnings=[];for(const enemy of enemies)if(!enemy.dead)damageEnemy(enemy,7+profile.state.upgrades.reactor);if(boss)damageBoss(10+profile.state.upgrades.reactor*2);rings.push({x:player.x,y:player.y,r:10,max:Math.min(W,440),life:.65,total:.65,c:'#bceff6'});pulseSound(100,.3,'sine',.07);document.dispatchEvent(new CustomEvent('imran:haptic',{detail:{kind:'pulse'}}));return true}
function dronePosition(){return {x:clamp(player.x+Math.cos(gameTime*1.9)*64,18,W-18),y:player.y-6+Math.sin(gameTime*1.9)*25}}
function updateDrone(){const u=profile.state.upgrades.wingman;if(!u||gameTime-lastDrone<Math.max(.38,.95-u*.13))return;lastDrone=gameTime;const p=dronePosition();shots.push({x:p.x,y:p.y-14,vx:0,vy:-960,r:3,d:.75+u*.32,t:'laser',life:2.2,angle:0,trail:[],pierce:1,hit:new Set()})}
function drawDrone(){if(!player||!profile.state.upgrades.wingman||!running)return;const p=dronePosition();x.save();x.translate(p.x,p.y);glow(0,0,26,'#8bdfff',.27);poly([[-13,4],[-6,-6],[0,-14],[6,-6],[13,4],[5,1],[0,9],[-5,1]],'#6a9db5','#c6eaff',1);circle(0,0,3,'#ddfbff');x.restore()}
function drawWorldDetails(){x.save();x.globalAlpha=.15;x.strokeStyle=world.color;x.fillStyle=world.color;x.lineWidth=1;const offset=gameTime*14;for(let i=0;i<12;i++){const px=((i*113.7)%Math.max(1,W)),py=((i*173.1+offset*(.3+i%3*.3))%(H+180))-90;if(world.style==='ice'){poly([[px,py-34],[px+11,py],[px,py+45],[px-14,py]],null,world.color)}else if(world.style==='dust'){x.beginPath();x.moveTo(px,py);x.lineTo(px-24,py+9);x.stroke()}else if(world.style==='storm'){x.beginPath();x.moveTo(px,py);x.lineTo(px+18,py+18);x.lineTo(px+5,py+29);x.lineTo(px+29,py+57);x.stroke()}else if(world.style==='hive'){const points=Array.from({length:6},(_,j)=>[px+Math.cos(j*TAU/6)*44,py+Math.sin(j*TAU/6)*44]);poly(points,null,world.color)}else if(world.style==='nebula'){x.globalAlpha=.025;x.beginPath();x.ellipse(px,py,100+i*2,34,-.4,0,TAU);x.fill()}}if(world.style==='orbit'){x.globalAlpha=.18;x.beginPath();x.ellipse(W*.12,H*.46,105,22,.6,0,TAU);x.stroke();x.beginPath();x.ellipse(W*.12,H*.46,85,17,.6,0,TAU);x.stroke()}x.restore()}
function ensureAudio(){if(!soundOn||audioContext)return;try{const Constructor=window.AudioContext||window.webkitAudioContext;if(Constructor){audioContext=new Constructor();audioContext.resume().catch(()=>{})}}catch(error){soundOn=false}}
function musicTick(now){if(!soundOn||!profile.state.settings.music||paused||document.hidden||!audioContext||audioContext.state==='suspended'||now<musicNext)return;musicNext=now+410;try{const frequencies=[110,164.81,220,146.83,196,246.94,164.81,130.81],osc=audioContext.createOscillator(),gain=audioContext.createGain(),t=audioContext.currentTime;osc.type='sine';osc.frequency.value=frequencies[musicNote++%frequencies.length]*(running?1: .5);gain.gain.setValueAtTime(.001,t);gain.gain.linearRampToValueAtTime(.018,t+.09);gain.gain.exponentialRampToValueAtTime(.001,t+.75);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t);osc.stop(t+.8)}catch(error){}}
function returnToLobby(page='home'){running=false;paused=false;clearInput();for(const item of [ui.top,ui.weapons,ui.hint,ui.fire,ui.pause,ui.over,ui.announce,ui.bossHud,el('pauseMenu')])item.classList.add('hidden');ui.start.classList.remove('hidden');document.dispatchEvent(new CustomEvent('imran:lobby',{detail:{page}}));profile.save()}
document.addEventListener('imran:launch',event=>{const detail=event.detail||{};runMode=detail.mode==='endless'?'endless':'campaign';selectedMission=Math.floor(Number(detail.mission)||1);if(runMode==='campaign'&&(selectedMission<1||selectedMission>profile.state.unlocked))return;startGame()});
document.addEventListener('imran:pause',()=>setPaused(true));document.addEventListener('imran:settings',()=>{difficulty=profile.state.settings.difficulty;if(!profile.state.settings.sound&&audioContext)audioContext.suspend().catch(()=>{})});
el('resumeBtn').addEventListener('click',()=>setPaused(false));el('restartMission').addEventListener('click',startGame);el('returnMenu').addEventListener('click',()=>returnToLobby());el('resultMenu').addEventListener('click',()=>returnToLobby('campaign'));el('nextMission').addEventListener('click',()=>{runMode='campaign';selectedMission=Math.min(30,level+1);if(profile.select(selectedMission))startGame()});

// Each pointer retains its acquired role: releasing fire never releases movement.
function stopMoving(){movePointerId=null;moveStart=null;playerStart=null;if(player)target={x:player.x,y:player.y}}
function clearInput(){stopMoving();fireTouches.clear();keys.clear();if(ui.fire)ui.fire.classList.remove('pressed')}
function setPaused(value){if(!running)return;paused=Boolean(value);clearInput();last=performance.now();ui.pause.textContent=paused?'▶':'⏸';ui.pause.setAttribute('aria-label',paused?'Продолжить':'Пауза');el('pauseMenu').classList.toggle('hidden',!paused);setText(el('pauseMission'),runMode==='endless'?'Бесконечный полёт · волна '+level:'Миссия '+level+' · '+mission.name);if(audioContext){if(paused)audioContext.suspend().catch(()=>{});else if(soundOn)audioContext.resume().catch(()=>{})}}
function capture(element,event){try{element.setPointerCapture(event.pointerId)}catch(error){}}
c.addEventListener('pointerdown',e=>{if(!running||paused||movePointerId!==null||(e.pointerType==='mouse'&&e.button!==0)||fireTouches.has(e.pointerId))return;e.preventDefault();movePointerId=e.pointerId;moveStart={x:e.clientX,y:e.clientY};playerStart={x:player.x,y:player.y};target={...playerStart};capture(c,e)});
c.addEventListener('pointermove',e=>{if(!running||paused||e.pointerId!==movePointerId)return;e.preventDefault();const b=playerBounds();target.x=clamp(playerStart.x+(e.clientX-moveStart.x)*(profile.state.ship==='swift'?1.25:profile.state.ship==='bastion'?.88:1),b.left,b.right);target.y=clamp(playerStart.y+(e.clientY-moveStart.y)*(profile.state.ship==='swift'?1.25:profile.state.ship==='bastion'?.88:1),b.top,b.bottom)});
function endPointer(e){if(e.pointerId===movePointerId)stopMoving();fireTouches.delete(e.pointerId);ui.fire.classList.toggle('pressed',fireTouches.size>0)}
ui.fire.addEventListener('pointerdown',e=>{if(!running||paused||(e.pointerType==='mouse'&&e.button!==0)||e.pointerId===movePointerId)return;e.preventDefault();fireTouches.add(e.pointerId);ui.fire.classList.add('pressed');capture(ui.fire,e);if(profile.state.settings.autoFire)activateSpecial();else shoot()});
for(const type of ['pointerup','pointercancel'])addEventListener(type,endPointer);
c.addEventListener('lostpointercapture',endPointer);ui.fire.addEventListener('lostpointercapture',endPointer);
ui.fire.addEventListener('contextmenu',e=>e.preventDefault());c.addEventListener('contextmenu',e=>e.preventDefault());
ui.weapons.addEventListener('click',e=>{const button=e.target.closest('.weapon');if(button&&running&&!paused)setWeapon(button.dataset.w)});
ui.pause.addEventListener('click',()=>setPaused(!paused));el('startBtn').addEventListener('click',()=>{runMode='campaign';selectedMission=profile.state.selected;startGame()});el('again').addEventListener('click',startGame);
const movementCodes=new Set(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyW','KeyA','KeyS','KeyD']);
addEventListener('keydown',e=>{if(!running)return;if(e.code==='KeyP'||e.code==='Escape'){if(!e.repeat)setPaused(!paused);e.preventDefault();return}if(paused)return;const w=Object.keys(stats)[Number(e.key)-1];if(w)setWeapon(w);if(movementCodes.has(e.code)){e.preventDefault();keys.add(e.code)}if(e.code==='Space'){if(profile.state.settings.autoFire&&!e.repeat)activateSpecial();fireTouches.add('key');ui.fire.classList.add('pressed');e.preventDefault()}});
addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='Space'){fireTouches.delete('key');ui.fire.classList.toggle('pressed',fireTouches.size>0)}});
addEventListener('blur',()=>setPaused(true));addEventListener('pagehide',()=>setPaused(true));document.addEventListener('visibilitychange',()=>{if(document.hidden)setPaused(true)});
if(ui.difficulty){for(const button of ui.difficulty.querySelectorAll('[data-difficulty]'))button.classList.toggle('selected',button.dataset.difficulty===difficulty);ui.difficulty.addEventListener('click',e=>{const button=e.target.closest('[data-difficulty]');if(!button||!difficulties[button.dataset.difficulty]||running)return;difficulty=button.dataset.difficulty;profile.setting('difficulty',difficulty);for(const option of ui.difficulty.querySelectorAll('[data-difficulty]'))option.classList.toggle('selected',option===button);try{localStorage.setItem('imranFleetDifficulty',difficulty)}catch(error){}})}
if(ui.sound)ui.sound.addEventListener('click',()=>{soundOn=!soundOn;if(soundOn){try{const Constructor=window.AudioContext||window.webkitAudioContext;if(!Constructor){soundOn=false;return}audioContext=audioContext||new Constructor();audioContext.resume().catch(()=>{});pulseSound(620,.1,'sine',.06)}catch(error){soundOn=false}}profile.setting('sound',soundOn);ui.sound.textContent=soundOn?'ВКЛ.':'ВЫКЛ.';ui.sound.setAttribute('aria-pressed',String(soundOn));ui.sound.setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук')});
ui.sound.textContent=soundOn?'ВКЛ.':'ВЫКЛ.';ui.sound.setAttribute('aria-pressed',String(soundOn));ui.sound.setAttribute('aria-label',soundOn?'Выключить звук':'Включить звук');resize();stars=Array.from({length:110},()=>({x:Math.random()*W,y:Math.random()*H,z:rnd(.25,1),tw:rnd(0,TAU)}));setText(ui.best,best);el('startBtn').disabled=false;document.dispatchEvent(new CustomEvent('imran:settings'));if(el('loading'))el('loading').classList.add('hidden');requestAnimationFrame(frame);
})();
