(()=>{'use strict';
const C=ImranCampaign,P=C.profile,el=id=>document.getElementById(id);
let region=Math.floor((P.state.selected-1)/5),page='home',selected=P.state.selected;
const weaponNames={laser:'ЛАЗЕР',spread:'ВЕЕР',plasma:'ПЛАЗМА',rockets:'РАКЕТЫ',beam:'ЛУЧ'};
function node(tag,className,text){const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n}
function brief(){const m=C.mission(selected),unlocked=selected<=P.state.unlocked;el('briefRegion').textContent=C.worlds[m.world].name.toUpperCase()+' / '+String(m.id).padStart(2,'0');el('briefName').textContent=m.name;el('briefStory').textContent=m.brief;el('briefGoal').textContent=C.goalText(m);el('briefTime').textContent=Math.ceil(m.duration/60)+'–'+Math.ceil((m.duration+45)/60)+' мин';el('launchMission').disabled=!unlocked;el('launchMission').textContent=unlocked?'ВЫЛЕТ ↗':'СНАЧАЛА ПРЕДЫДУЩАЯ МИССИЯ';}
function renderMap(){const s=P.state;el('worldTabs').replaceChildren();C.worlds.forEach((w,i)=>{const b=node('button','world-tab'+(region===i?' selected':''));b.type='button';b.dataset.world=i;b.setAttribute('aria-pressed',String(region===i));b.append(node('small',null,String(i+1).padStart(2,'0')+' / '+w.code),node('strong',null,w.name));b.style.setProperty('--world',w.color);el('worldTabs').append(b)});el('missionGrid').replaceChildren();C.missions.filter(m=>m.world===region).forEach(m=>{const locked=m.id>s.unlocked,record=s.missions[m.id],b=node('button','mission-tile'+(selected===m.id?' selected':'')+(locked?' locked':''));b.type='button';b.dataset.mission=m.id;b.setAttribute('aria-label','Миссия '+m.id+'. '+m.name+(locked?'. Заблокирована':record?'. Медали '+record.stars+' из 3':'. Доступна'));b.setAttribute('aria-pressed',String(selected===m.id));b.append(node('span','mission-number',String(m.id).padStart(2,'0')),node('strong',null,m.name),node('span','mission-type',m.formation==='siege'?'ШТУРМ':m.formation==='crossfire'?'ПЕРЕХВАТ':'ОПЕРАЦИЯ'),node('span','mission-stars',locked?'ЗАКРЫТО':record?'◆'.repeat(record.stars)+'◇'.repeat(3-record.stars):'◇ ◇ ◇'));el('missionGrid').append(b)});brief();}
function renderHangar(){const s=P.state;el('upgradeGrid').replaceChildren();for(const [id,u] of Object.entries(C.upgrades)){const lv=s.upgrades[id],max=lv>=u.max,cost=P.cost(id),card=node('article','upgrade-card'),b=node('button','upgrade-buy',max?'МАКСИМУМ':cost+' ◈');b.type='button';b.dataset.upgrade=id;b.disabled=max||s.credits<cost;b.setAttribute('aria-label','Улучшить '+u.name+', уровень '+lv+', стоимость '+cost+' сплава');card.append(node('div','upgrade-level',String(lv).padStart(2,'0')+' / '+u.max),node('h4',null,u.name),node('p',null,u.text),b);el('upgradeGrid').append(card)}el('shipChoices').replaceChildren();for(const ship of C.ships){const owned=s.ships.includes(ship.id),active=s.ship===ship.id,locked=s.unlocked<ship.unlock,b=node('button','ship-choice'+(active?' selected':''));b.type='button';b.dataset.ship=ship.id;b.disabled=locked||(!owned&&s.credits<ship.cost);b.setAttribute('aria-pressed',String(active));b.append(node('strong',null,ship.name),node('small',null,active?'ВЫБРАНА':locked?'С МИССИИ '+ship.unlock:owned?ship.tag:ship.cost+' ◈'));el('shipChoices').append(b)}const ship=C.ships.find(v=>v.id===s.ship);el('shipName').textContent=ship.name.toUpperCase();el('shipDescription').textContent=ship.text;el('arsenalSummary').replaceChildren();for(const [id,name] of Object.entries(weaponNames))el('arsenalSummary').append(node('span',s.arsenal[id]?'owned':'locked',s.arsenal[id]?name:'🔒 '+name));}
function render(){const s=P.state,m=C.mission(s.selected),cleared=Object.keys(s.missions).length,medals=Object.values(s.missions).reduce((sum,v)=>sum+v.stars,0);el('credits').textContent=s.credits;el('continueLabel').textContent='МИССИЯ '+String(m.id).padStart(2,'0')+' / '+m.name.toUpperCase();el('continueText').textContent=C.worlds[m.world].name+' · '+m.brief;el('continueButton').textContent=cleared?'ПРОДОЛЖИТЬ КАМПАНИЮ':'НАЧАТЬ КАМПАНИЮ';el('campaignSummary').textContent=cleared+' / 30 пройдено · '+medals+' медалей';el('medalTotal').textContent=medals+' / 90 ◆';el('endlessRecord').textContent=s.endlessBest?'Рекорд: '+s.endlessBest:'Нарастающие волны и боссы';el('progressSummary').textContent=cleared?cleared+' / 30 МИССИЙ · '+medals+' МЕДАЛЕЙ':'ШЕСТЬ МИРОВ. ТВОЙ ПУТЬ НАЧИНАЕТСЯ.';el('saveStatus').textContent=P.storageAvailable?'Прогресс сохраняется на этом устройстве.':'В этом браузере сохранение недоступно. Текущий прогресс хранится до закрытия игры.';for(const button of document.querySelectorAll('[data-setting]')){const on=s.settings[button.dataset.setting];button.textContent=on?'ВКЛ.':'ВЫКЛ.';button.setAttribute('aria-label',(button.closest('.setting-row')?.querySelector('strong')?.textContent||button.dataset.setting)+': '+(on?'включено':'выключено'));button.setAttribute('aria-pressed',String(on));button.classList.toggle('enabled',on)}for(const button of document.querySelectorAll('[data-difficulty]')){const on=button.dataset.difficulty===s.settings.difficulty;button.classList.toggle('selected',on);button.setAttribute('aria-pressed',String(on))}if(page==='campaign')renderMap();if(page==='hangar')renderHangar();}
function show(name){page=name;for(const name2 of ['home','campaign','hangar','settings','privacy'])el(name2+'Page').classList.toggle('hidden',name2!==name);el('start').classList.toggle('home-view',name==='home');render();el('start').scrollTop=0;}
function launch(id,mode='campaign'){if(mode==='campaign'&&!P.select(id))return;document.dispatchEvent(new CustomEvent('imran:launch',{detail:{mission:id,mode}}));}
el('homeBtn').addEventListener('click',()=>show('home'));el('campaignBtn').addEventListener('click',()=>{selected=P.state.selected;region=C.mission(selected).world;show('campaign')});el('hangarBtn').addEventListener('click',()=>show('hangar'));el('settingsBtn').addEventListener('click',()=>show('settings'));el('privacyBtn').addEventListener('click',()=>show('privacy'));el('endlessBtn').addEventListener('click',()=>launch(1,'endless'));el('launchMission').addEventListener('click',()=>launch(selected));
el('worldTabs').addEventListener('click',e=>{const b=e.target.closest('[data-world]');if(!b)return;region=Number(b.dataset.world);selected=region*5+1;renderMap()});el('missionGrid').addEventListener('click',e=>{const b=e.target.closest('[data-mission]');if(!b)return;selected=Number(b.dataset.mission);if(selected<=P.state.unlocked)P.select(selected);renderMap()});el('upgradeGrid').addEventListener('click',e=>{const b=e.target.closest('[data-upgrade]');if(!b)return;const u=C.upgrades[b.dataset.upgrade];el('hangarNotice').textContent=P.buy(b.dataset.upgrade)?u.name+' улучшен. Ракета готова к следующему вылету.':'Недостаточно сплава.';render()});el('shipChoices').addEventListener('click',e=>{const b=e.target.closest('[data-ship]');if(!b)return;P.selectShip(b.dataset.ship);render()});
for(const b of document.querySelectorAll('[data-setting]'))b.addEventListener('click',()=>{P.setting(b.dataset.setting,!P.state.settings[b.dataset.setting]);render();document.dispatchEvent(new CustomEvent('imran:settings'))});
document.addEventListener('imran:lobby',e=>{selected=P.state.selected;region=C.mission(selected).world;show(e.detail?.page||'home')});document.addEventListener('imran:progress',render);document.addEventListener('imran:settings',render);show('home');
})();
